---
title: "Chapter21_2"
author: "Olof Rännbäck Garpinger"
date: "February 19, 2018"
output: html_document
---

Text formatting
----------------------------------------------------------------------------------------------------------------------
 *italic* or _italic_
 **bold** or __bold__
 `code`
 superscript^2^ and subscript~2~
 
 Headings
----------------------------------------------------------------------------------------------------------------------
# 1st Level Header
 
## 2nd Level Header
 
### 3rd Level Header

A footnote 2 [^1]
 
 Lists
----------------------------------------------------------------------------------------------------------------------

*   Bulleted list item 1

*   Item 2
    
    * Item 2a
    
    * Item 2b
    
1.  Numbered list item 1

1.  Item 2. The numbers are incremented automatically in the output.

Links and images
----------------------------------------------------------------------------------------------------------------------

<http://example.com>

[linked phrase](http://example.com)

Tables
----------------------------------------------------------------------------------------------------------------------

First Header | Second Header | Third Header
-------------|---------------|---------------
Content Cell | Content Cell  | Content Cell
Content Cell | Content Cell  | Content Cell

```{r}
library(ggplot2)
library(dplyr)
diamonds %>% 
  head(10)

```

> block quote

*** 

A footnote [^2]

[^1]: Here is the footnote.
[^2]: Here is the footnote 2.

```{r by-name, eval = F}
hej = 1
hej
```

```{r}
knitr::kable(
  mtcars[1:5, ],
  caption = "A knitr kable."
)
```















    

    